// import { PostDbModel } from "../types/studio.types";

// export const MOCK_POSTS: PostDbModel[] = [
//     {
//         id: "post_1",
//         title: "Ultimate Burger Stack",
//         description: "Juicy double patty burger with cheese.",
//         contentType: "DISH",
//         mediaType: "IMAGE",
//         isPinned: true,
//         likeCount: 980,
//         commentCount: 120,
//         userId: "user_1",
//         createdAt: new Date("2026-03-01"),
//         updatedAt: new Date("2026-03-02"),
//         media: Array.from({ length: 5 }).map((_, i) => ({
//             id: `media_1_${i}`,
//             url: `/images/burger_${i}.jpg`,
//             type: "IMAGE",
//             order: i + 1,
//             postId: "post_1",
//             createdAt: new Date(),
//             updatedAt: new Date(),
//         })),
//     },

//     {
//         id: "post_2",
//         title: "Creamy Alfredo Pasta",
//         description: "Step-by-step creamy pasta recipe.",
//         contentType: "RECIPE",
//         mediaType: "VIDEO",
//         isPinned: false,
//         likeCount: 210,
//         commentCount: 18,
//         userId: "user_2",
//         createdAt: new Date(),
//         updatedAt: new Date(),
//         media: [
//             {
//                 id: "media_2",
//                 url: "/videos/alfredo.mp4",
//                 type: "VIDEO",
//                 order: 1,
//                 postId: "post_2",
//                 createdAt: new Date(),
//                 updatedAt: new Date(),
//             },
//         ],
//     },

//     // {
//     //     id: "post_3",
//     //     title: "Rainbow Fruit Bowl",
//     //     description: "Healthy and colorful fruits.",
//     //     contentType: "DISH",
//     //     mediaType: "IMAGE",
//     //     isPinned: false,
//     //     likeCount: 75,
//     //     commentCount: 6,
//     //     userId: "user_3",
//     //     createdAt: new Date(),
//     //     updatedAt: new Date(),
//     //     media: Array.from({ length: 10 }).map((_, i) => ({
//     //         id: `media_3_${i}`,
//     //         url: `/images/fruits_${i}.jpg`,
//     //         type: "MULTI_IMAGE",
//     //         order: i + 1,
//     //         postId: "post_3",
//     //         createdAt: new Date(),
//     //         updatedAt: new Date(),
//     //     })),
//     // },

//     {
//         id: "post_4",
//         title: "Sizzling Steak",
//         description: "Medium rare perfection.",
//         contentType: "DISH",
//         mediaType: "IMAGE",
//         isPinned: true,
//         likeCount: 640,
//         commentCount: 70,
//         userId: "user_4",
//         createdAt: new Date(),
//         updatedAt: new Date(),
//         media: [
//             {
//                 id: "media_4_1",
//                 url: "/images/steak.jpg",
//                 type: "IMAGE",
//                 order: 1,
//                 postId: "post_4",
//                 createdAt: new Date(),
//                 updatedAt: new Date(),
//             },
//         ],
//     },

//     // {
//     //     id: "post_5",
//     //     title: "Homemade Sushi",
//     //     description: "Rolling sushi at home.",
//     //     contentType: "RECIPE",
//     //     mediaType: "IMAGE",
//     //     isPinned: false,
//     //     likeCount: 330,
//     //     commentCount: 42,
//     //     userId: "user_5",
//     //     createdAt: new Date(),
//     //     updatedAt: new Date(),
//     //     media: Array.from({ length: 3 }).map((_, i) => ({
//     //         id: `media_5_${i}`,
//     //         url: `/images/sushi_${i}.jpg`,
//     //         type: i === 0 ? "IMAGE" : "MULTI_IMAGE",
//     //         order: i + 1,
//     //         postId: "post_5",
//     //         createdAt: new Date(),
//     //         updatedAt: new Date(),
//     //     })),
//     // },

//     // {
//     //     id: "post_6",
//     //     title: "Street Tacos",
//     //     description: "Authentic Mexican tacos.",
//     //     contentType: "DISH",
//     //     mediaType: "VIDEO",
//     //     isPinned: false,
//     //     likeCount: 510,
//     //     commentCount: 65,
//     //     userId: "user_6",
//     //     createdAt: new Date(),
//     //     updatedAt: new Date(),
//     //     media: [
//     //         {
//     //             id: "media_6",
//     //             url: "/videos/tacos.mp4",
//     //             type: "VIDEO",
//     //             order: 1,
//     //             postId: "post_6",
//     //             createdAt: new Date(),
//     //             updatedAt: new Date(),
//     //         },
//     //     ],
//     // },

//     // {
//     //     id: "post_7",
//     //     title: "Chocolate Lava Cake",
//     //     description: "Melting center dessert.",
//     //     contentType: "RECIPE",
//     //     mediaType: "IMAGE",
//     //     isPinned: true,
//     //     likeCount: 870,
//     //     commentCount: 110,
//     //     userId: "user_7",
//     //     createdAt: new Date(),
//     //     updatedAt: new Date(),
//     //     media: Array.from({ length: 7 }).map((_, i) => ({
//     //         id: `media_7_${i}`,
//     //         url: `/images/lava_${i}.jpg`,
//     //         type: "MULTI_IMAGE",
//     //         order: i + 1,
//     //         postId: "post_7",
//     //         createdAt: new Date(),
//     //         updatedAt: new Date(),
//     //     })),
//     // },

//     // {
//     //     id: "post_8",
//     //     title: "Iced Coffee Aesthetic",
//     //     description: "Chill coffee vibes.",
//     //     contentType: "DISH",
//     //     mediaType: "IMAGE",
//     //     isPinned: false,
//     //     likeCount: 190,
//     //     commentCount: 12,
//     //     userId: "user_8",
//     //     createdAt: new Date(),
//     //     updatedAt: new Date(),
//     //     media: [
//     //         {
//     //             id: "media_8_1",
//     //             url: "/images/coffee.jpg",
//     //             type: "IMAGE",
//     //             order: 1,
//     //             postId: "post_8",
//     //             createdAt: new Date(),
//     //             updatedAt: new Date(),
//     //         },
//     //         {
//     //             id: "media_8_2",
//     //             url: "/images/coffee_2.jpg",
//     //             type: "MULTI_IMAGE",
//     //             order: 2,
//     //             postId: "post_8",
//     //             createdAt: new Date(),
//     //             updatedAt: new Date(),
//     //         },
//     //     ],
//     // },

//     // {
//     //     id: "post_9",
//     //     title: "Fried Chicken Crunch",
//     //     description: "Golden crispy chicken.",
//     //     contentType: "DISH",
//     //     mediaType: "VIDEO",
//     //     isPinned: false,
//     //     likeCount: 720,
//     //     commentCount: 95,
//     //     userId: "user_9",
//     //     createdAt: new Date(),
//     //     updatedAt: new Date(),
//     //     media: [
//     //         {
//     //             id: "media_9",
//     //             url: "/videos/chicken.mp4",
//     //             type: "VIDEO",
//     //             order: 1,
//     //             postId: "post_9",
//     //             createdAt: new Date(),
//     //             updatedAt: new Date(),
//     //         },
//     //     ],
//     // },

//     // {
//     //     id: "post_10",
//     //     title: "Vegan Buddha Bowl",
//     //     description: "Healthy vegan meal prep.",
//     //     contentType: "RECIPE",
//     //     mediaType: "IMAGE",
//     //     isPinned: false,
//     //     likeCount: 260,
//     //     commentCount: 28,
//     //     userId: "user_10",
//     //     createdAt: new Date(),
//     //     updatedAt: new Date(),
//     //     media: Array.from({ length: 4 }).map((_, i) => ({
//     //         id: `media_10_${i}`,
//     //         url: `/images/buddha_${i}.jpg`,
//     //         type: "MULTI_IMAGE",
//     //         order: i + 1,
//     //         postId: "post_10",
//     //         createdAt: new Date(),
//     //         updatedAt: new Date(),
//     //     })),
//     // },
// ];