  feat-backup-dev-26-04[m
  feat-forget-password[m
  feat-landing-page[m
  feat-onboarding[m
  feat-profile[m
  feat-sign-in[m
  feat-sign-up[m
  feat-studio-and-publication[m
  feat-update-account[m
  feat-update-profile[m
  feat-verify-email[m
* [32mmain[m
  new-main[m
  product-management[m
  qa[m
  style-forget-password[m
  style-onboarding[m
  style-sign-in[m
  style-update-profile[m
