
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import StoreProvider from './StoreProvider'
import Image from 'next/image'
import { cn } from '@/utils/shadcn.utils'
import RouteGuardProvider from './RouteGuardProvider'
import { Toaster } from '@/components/ui/sonner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={cn(inter.className, "relative min-h-screen h-fit bg-auth-gradient")}>
          <Image
            src={'/sign-up/auth-bck.png'}
            fill
            alt='bck'
            className='absolute top-0 left-0 -z-10 inset-0 object-cover opacity-30'
          ></Image>
          <div>
            {children}
          </div>
          <Toaster position='bottom-right'></Toaster>
        </body>
      </html>
    </StoreProvider>
  )
}
