
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import StoreProvider from './StoreProvider'
import Image from 'next/image'
import { relative } from 'path'
const inter = Inter({ subsets: ['latin'] })
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={ cn(inter.className ,`relative bg-auth-gradient`)}>
          <Image
                src={'/sign-up/auth-bck.png'}
                fill
                alt='bck'
                className='absolute top-0 left-0 -z-10 object-cover opacity-30'
            ></Image>
          <div className=''>
            {children}
          </div>
          </body>
      </html>
    </StoreProvider>
  )
}
